### ISSUE TITLE
Faltan cosas de clase

### ISSUE THREAD

**Issue by lEdgaar** [jeehvi/GameSwift#1]
Buenas Javi Gil,
Por lo que puedo observar, esta actividad no esta totalmente acabada, por favor si es tan amable de una vez acabada mandármela por correo se lo agradecería.
Atentamente el que se sienta al lado tuya. Salutacions

**Comment by lEdgaar** [comment]
JAJAJAA PD: No intentes eliminarla porque ya la tengo :)

**Comment by alin19xx** [comment]
alexlinsegarra@gmail.com

**Comment by lEdgaar** [comment]
Buenos días Javi Gil, le vuelvo a escribir porque esta práctica de clase de ayer a hoy no tenido ningún cambios, por favor deja de hacer el vago y ponte a hacer commits.
Saludos!!!!!!
